version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - $PWD/promtail-config.yml:/etc/promtail/config.yml
      - /home/eddy/demo1.log:/data/demo1.log
      - /home/eddy/demo2.log:/data/demo2.log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.2.4
    ports:
      - "3000:3000"
    networks:
      - loki