server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: demologs
  static_configs:
  - targets:
      - localhost
    labels:
      job: demo1
      __path__: /data/demo1.log
  - targets:
      - localhost
    labels:
      job: demo2
      __path__: /data/demo2.log
